## Preliminaries

In [272]:
import numpy
import matplotlib
import matplotlib.pyplot as plt
from scipy.io.wavfile import read as wavread
from scipy.io.wavfile import write as wavwrite

%matplotlib notebook

## File operations

Read the helloword WAV file.

Convert the stereo file to mono.

In [273]:
[samplerate, x] = wavread("/Users/serenafaruque/Dropbox/helloworld.wav")
x=x[:,0]

x

array([ -10591,  -30751,  -69097, ..., -383306, -555495, -769417], dtype=int32)

View sample rate of file. The sampling rate is how many data points were recorded every second.

In [274]:
samplerate

44100

View length of file. This is how many data points we have.

In [275]:
len(x)

93120

Writing a WAV file. You will need to specify a path, the sampling rate, and the file you would like to write.

In [276]:
wavwrite("/Users/serenafaruque/Dropbox/helloworld2.wav",44100,x)

Experiment with making your own wav file, reading it into Python, examining the sampling rate and length of the file, and writing it yourself!

## Manipulating sound

Changing volume (the hard way). If the multiply the numbers, they will create a larger signal and make a louder sound.

In [277]:
y = x*2
y

array([  -21182,   -61502,  -138194, ...,  -766612, -1110990, -1538834], dtype=int32)

Check it out!

In [278]:
wavwrite("/Users/serenafaruque/Dropbox/helloworldLOUD.wav",44100,y)

Change the volume on your own, experiment!

We can also make it faster or slower, easily, by changing the sampling rate.

In [279]:
wavwrite("/Users/serenafaruque/Dropbox/helloworldFAST.wav",88200,x)

Change the speed on your own, experiment!

We can string multiple arrays together (we call this concatentation).

In [280]:
z = numpy.concatenate((x,y),axis=0)
wavwrite("/Users/serenafaruque/Dropbox/helloworldCON.wav",44100,z)

Finally, we can add values from different points in time, to create different effects.

In [281]:
t = x

delay = 1
coefficient = 0.5

for i in range(delay,len(t)):
    t[i]=t[i-delay]
    
wavwrite("/Users/serenafaruque/Dropbox/helloworldFILTER.wav",44100,t)
t

array([-10591, -10591, -10591, ..., -10591, -10591, -10591], dtype=int32)

Do you see patterns in what works for the delays and coefficients?

In [282]:
x

array([-10591, -10591, -10591, ..., -10591, -10591, -10591], dtype=int32)

Use the tools we have discussed to make your very own clip! 